version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: recipe_db
    restart: always
    environment:
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: recipe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: recipe_backend
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: recipe_db
      POSTGRES_PORT: 5432
      ENVIRONMENT: development
      DEBUG: "True"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads

volumes:
  postgres_data:
  backend_uploads:


